language: python
python:
- '3.6'
- '3.7'
env:
- DJANGO_VERSION=1.9.5
services:
- mysql
install:
- pip3 install -r requirements.txt
script: python3 manage.py test
notifications:
  email:
    recipients:
    - maoyutao1006@163.com
before_install:
- openssl aes-256-cbc -K $encrypted_3828251df16f_key -iv $encrypted_3828251df16f_iv
  -in configs.json.enc -out configs.json -d
