language: python
python:
  - "3.6"
  - "3.7"
env:
  - DJANGO_VERSION=1.9.5
services:
  - mysql
install: 
 - pip3 install -r requirements.txt
script: python3 manage.py test
notifications:
  email:
    recipients:
      - maoyutao1006@163.com